# Generated by Django 3.0.4 on 2020-04-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=300)),
                ('cimg', models.ImageField(upload_to='images/')),
                ('cauthor', models.CharField(max_length=100)),
                ('cprice', models.FloatField()),
            ],
        ),
    ]
